### PR TITLE
new Date should return frozen date clone

### LINKED ISSUE #12: Changing a date after freezing also changes the frozen date
It looks like `new Date()` should return a new instance of the frozen date:

```javascript
var tk = require('timekeeper');
tk.freeze(new Date());

console.log(new Date()); // Wed Sep 30 2015 14:25:22 GMT+0000 (UTC)

var date = new Date();
date.setFullYear(2020); 

console.log(date); // Wed Sep 30 2020 14:25:22 GMT+0000 (UTC)

console.log(new Date()); // Wed Sep 30 2020 14:25:22 GMT+0000 (UTC)
```

Thanks!

### PR DESCRIPTION
**Pull request by joanniclaborde**
Fixes #12

### CODE REVIEW

**Comment by bendoh** [comment]
:+1:  Please merge this. It failed CI because of a temporary blip it seems but is necessary.

**Comment by vesln** [comment]
@bendoh would you like me to give you push access so you can merge and make sure that everything works as expected?

**Comment by bendoh** [comment]
Heh, sure, I have some tweaks to offer myself.

**Comment by LinusU** [comment]
@bendoh @vesln Any updates on this?

**Comment by vesln** [comment]
@LinusU seems like it's merged in already, @bendoh can you release a new version on npm?

**Comment by freewil** [comment]
@vesln can you do the release? I'd be happy to do it if you add me to the repo and npm package.

**Comment by vesln** [comment]
@freewil yep, will do! if u are interested in maintaining - happy to give you full access, just lmk

**Comment by freewil** [comment]
Yeah - I'd be happy to

**Comment by LinusU** [comment]
I would be very interested to help maintaining as well 👍

**Comment by vesln** [comment]
awesome, please let me know your npm usernames and I will add you

re this issue - https://github.com/vesln/timekeeper/pull/15 is not merged yet, please make sure it works as expected before merging and releasing. 

thanks <3

**Comment by freewil** [comment]
> awesome, please let me know your npm usernames and I will add you

freewil

**Comment by vesln** [comment]
@freewil you are good to go, @LinusU let me know what your npm username is and you will be added as well

**Comment by LinusU** [comment]
`linusu`, thanks :)

**Comment by vesln** [comment]
@LinusU - done;

thanks to both of you for stepping in!

**Comment by LinusU** [comment]
Landed in #18

**Comment by joanniclaborde** [comment]
Thanks!! I had forgotten about that pull request, haha!

**Pull request closed without merging**
