### PR TITLE
feat: makes timekeeper.travel work if currently frozen

### PR DESCRIPTION
**Pull request by keenahn**
Closes https://github.com/vesln/timekeeper/issues/26

@vesln

### CODE REVIEW

**Comment by keenahn** [comment]
@vesln how about it? :)

**Comment by keenahn** [comment]
Good question. I suppose it is a breaking change if anyone was using the package before and relying on the previous behavior. Should we bump the major version?

**Comment by keenahn** [comment]
@vesln

**Comment by vesln** [comment]
fine by me, let's do this!

**Comment by freewil** [comment]
Great, will do a v2 release

**Pull request merged**
