### PR TITLE
Test if returned value is thenable

### PR DESCRIPTION
**Pull request by LinusU**
@nwtgck would be happy if you could review this ☺️ 

The change is to allow a Promise not constructed with the global `Promise` so be accepted. It follows the concept of "Thenables"...

### CODE REVIEW

**Comment by nwtgck** [comment]
@LinusU 

Your PR is more general than #34, it allows the users to use an object with `.then()`  method not only `Promise` instance, and it `reset()` when it has an error in some reason.

LGTM 👍

**Comment by nwtgck** [comment]
@LinusU 
How about null check? Because ` typeof null` is "object". It has an error in `null.then`.

**Comment by LinusU** [comment]
Good catch, fixing!

**Comment by LinusU** [comment]
@nwtgck fixed, LGTM?

**Comment by nwtgck** [comment]
@LinusU 
Great fix and great test! LGTM 👍

**Comment by LinusU** [comment]
Thanks!

**Comment by LinusU** [comment]
Released as 2.2.0, truly sorry for the very long delay @nwtgck ❤️

**Pull request merged**
